//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int MaHS { get; set; }
        public string TenHS { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    }
}
